namespace: "softasap"
name: "vault_box"
description: Configures hashicorp vault machine
version: "0.0.1"
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
  "softasap.sa-hashicorp-vault": ">=0.0.1"
  "softasap.sa-nginx": ">=0.0.1"
  "softasap.sa-acme-sh": ">=0.0.1"
license:
    - "MIT"
tags:
    - softasap
    - hashicorp
    - vault
repository: "https://github.com/oops-to-devops/vault-box"
documentation: "https://github.com/oops-to-devops/vault-box/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
